### ISSUE TITLE
Unload% ends the level instantly on Dustmod type levels

### ISSUE THREAD

**Issue by cmann1** [cmann1/dustmod-issues#12]
It seems like the problem is that on non-normal maps, `was_run` is always set to false, which is used to check for unload%
(Skyhawk)

**Comment by msg555** [comment]
Updated so that unload triggers for Dustmod maps if the player would have otherwise been unloaded (although as a reminder Dustmod maps prevent the player from truely unloading). This also makes oob is now playable
