### ISSUE TITLE
Colour picker sliders show wrong values after updating from input

### ISSUE THREAD

**Issue by cmann1** [cmann1/dustmod-issues#16]
Possibly a bug in `colour_xform::update_from_colour ` that doesn't set the hsl values correctly.
(Alexspeedy)
https://discord.com/channels/83037671227658240/275015117236731905/836526960112173077

**Comment by msg555** [comment]
It does look like the existing implemention is blatantly wrong. e.g. it has

`l = max( r, max( g, b ) );`

Any thoughts on just hoisting the code out of the engine?

**Comment by cmann1** [comment]
Sounds good. Will make maintenance in the future easier if necessary

**Comment by msg555** [comment]
vec4, hx_colour, and colour_xform have been removed from the engine and now everything is using util/colour.hpp
