### ISSUE TITLE
DTD stops working

### ISSUE THREAD

**Issue by cmann1** [cmann1/dustmod-issues#25]
https://discord.com/channels/83037671227658240/276106941875355658/822933181241098260
https://discord.com/channels/83037671227658240/276106941875355658/846452525904298024

**Comment by msg555** [comment]
This is more than likely not a bug and a result of e.g. a key randomly being jammed on the keyboard preventing DTD from working correctly.

I'm not inclined to update DTD logic in the engine. If we wish to make any changes to the way DTD works we should do it script side and even then I'm not sure such a change is well justified.

**Comment by cmann1** [comment]
Understandable.
It almost definitely was not a jammed key though, the behaviour was consistent.
But I have no clue what caused it in the first place or why it fixed itself, and it hasn't happened again since (though I don't really use DTD).
