### ISSUE TITLE
In Dustmod unloaded entities are still detected by end flags

### ISSUE THREAD

**Issue by cmann1** [cmann1/dustmod-issues#26]
[unloadtest.zip](https://github.com/cmann1/dustmod-issues/files/6638197/unloadtest.zip)

Test: open the attached map, play, follow the gargoyle attached to the end flag down, take the zip back up.

In vanilla the unloaded entity is not detected and the level ends.
In dustmod, `get_entity_by_uid` doesn't return null and the level does not end.

**Comment by msg555** [comment]
Should be fixed
