### ISSUE TITLE
Seg fault on save state in Starstruck Coast

### ISSUE THREAD

**Issue by cmann1** [cmann1/dustmod-issues#3]
Caused by having a `timedate@` class field.
Not assigning anything to this field (leaving it null), or using a `timedata@` as a local variable are both fine.

(Alexspeedy)
https://discord.com/channels/83037671227658240/342175833089245184/845795875883450408

**Comment by msg555** [comment]
Should be fixed on master. I put a main3 in #codeforce with the patch
