### ISSUE TITLE
`text_input` does not return newlines

### ISSUE THREAD

**Issue by cmann1** [cmann1/dustmod-issues#42]
Maybe this is intended behaviour?
A related issue is that shift+enter no longer adds lines to text triggers.

**Comment by msg555** [comment]
text_input only includes printable characters. WM_CHAR gives slightly more than this but I had to cut it down to match what we get out of SDL2 for non-windows builds.

**Comment by cmann1** [comment]
I see.
Well it will be easy enough to reimplement in the trigger logic.
