### ISSUE TITLE
Unable to set input display opacity after zeroing it out

### ISSUE THREAD

**Issue by HolyKau** [cmann1/dustmod-issues#54]
Under Display -> Overlay -> Input Display Color, I'm unable to set a different opacity after setting it to 0 (dragging the slider all the way to the left).

I've tried both clicking Ok and pressing enter. I've tried moving the color picker dialog somewhere else but can't get the opacity to save. All the other sliders work and save fine.

Dustmod version: 21.9.1 win32_steam

**Comment by cmann1** [comment]
I 'm assuming this was just the issue with the colour picker alpha slider which will be fixed in the next release.
