### ISSUE TITLE
Hit-outcome manipulation

### ISSUE THREAD

**Issue by JonatanWaern** [cmann1/dustmod-issues#66]
Being able to change a hitbox outcome to miss, parry, hit (change to hit a bit redundant but), etc.. Which would actually affect both controllables (attacker and attacked) correctly based on the new outcome.

If it's sufficient, then a setter of hit_outcome in hitbox. I suspect this is too late though, and there'd need to be another callback that triggers a bit earlier that modifies how the hitbox hit-check actually happens.

**Comment by JonatanWaern** [comment]
A followup on this is that this could allow custom-made non-square hitboxes, if we indeed can callback and manipulate how the hitbox interaction is done.

**Comment by cmann1** [comment]
These should now be possible with the new `hit_outcome` setter and `on_hit_filter_callback` added to `hitbox` in the next release.
