### ISSUE TITLE
API interaction with some standard triggers

### ISSUE THREAD

**Issue by JonatanWaern** [cmann1/dustmod-issues#69]
Reading and writing information from
- fog triggers
- ambience/music triggers
- doors
- text
- camera nodes (not technically triggers)

**Comment by JonatanWaern** [comment]
I do not know to what extent this is already possible with varstruct

**Comment by msg555** [comment]
To some extent it is possible with the reflection/vars API. Many of these objects do not update their internal state correctly however if you modify their vars after they have been added to the scene so ymmv there. A more foolproof approach is to copy vars, modify vars, replace the entity when you need to make modifications.

I'm open to improving support for var modifications correclty updating internal state of specific objects. For many of the mentioned entities I suspect it will just work (camera nodes probably won't). An API to manipulate camera nodes is probably appropriate.
